(deftheme my-theme "my custom theme")
(custom-theme-set-faces
  'my-theme
  '(default ((t (:foreground "#ffffff" :background "#000000"))))
  '(cursor ((t (:background "#fff394"))))
  '(fringe ((t (:background "#1e011c"))))
  '(mode-line ((t (:foreground "#4c407d" :background "#828f76"))))
  '(region ((t (:background "#273a2b"))))
  '(font-lock-builtin-face ((t (:foreground "#84a2c2"))))
  '(font-lock-comment-face ((t (:foreground "#d29e14"))))
  '(font-lock-function-name-face ((t (:foreground "#b72fe4"))))
  '(font-lock-keyword-face ((t (:foreground "#13ee11"))))
  '(font-lock-string-face ((t (:foreground "#f36d70"))))
  '(font-lock-type-face ((t (:foreground"#f42ac8"))))
  '(font-lock-constant-face ((t (:foreground "#d40ca9"))))
  '(font-lock-variable-name-face ((t (:foreground "#3d40fa"))))
  '(minibuffer-prompt ((t (:foreground "#10c692" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'my-theme)
